### ISSUE TITLE
Define browser support

### ISSUE THREAD

**Issue by Dietr** [appuniversum/appuniversum#18]
We should probably define some level of browser support.

Our applications currently support the following browsers: Chrome, Safari and Firefox.
Maybe we can extend this with Microsoft Edge support.

**Comment by Wolfr** [comment]
Since “new Edge” uses the Chromium engine it seems reasonable to support it.

I would not support older browsers like IE11, although we could probably test and apply some fixes at some point to make it render reasonably well. So I would label that as “Partial support” (With guideline: avoid using CSS grid style components when you need legacy support / Remove animations by flagging a variable in the globals)

I would support Chrome (Desktop), Chrome (Android), Safari, Mobile Safari, Firefox and new Edge. I think that covers most usage.
